package cn.z.zai.dto.request.chat;
import com.fasterxml.jackson.annotation.JsonProperty;
import lombok.Data;

/**
 * A chat completion generated by GPT-3.5
 */
@Data
public class ChatCompletionChoice {

    /**
     * This index of this completion in the returned list.
     */
    Integer index;

    /**
     * The {@link ChatMessageRole#} message which was generated.
     */
    ChatMessage message;

    /**
     *
     */
    StreamChatMessage delta;

    /**
     * The reason why GPT-3 stopped generating, for example "length".
     */
    @JsonProperty("finish_reason")
    String finishReason;
}
